src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Adress::class)]
    private Collection $adresses;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Article::class)]
    private Collection $articles;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Profile $Profile = null;

    public function __construct()
    {
        $this->adresses = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getUser(): self
    {
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return Collection<int, Adress>
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdress(Adress $adress): self
    {
        if (!$this->adresses->contains($adress)) {
            $this->adresses->add($adress);
            $adress->setUser($this);
        }

        return $this;
    }

    public function removeAdress(Adress $adress): self
    {
        if ($this->adresses->removeElement($adress)) {
            // set the owning side to null (unless already changed)
            if ($adress->getUser() === $this) {
                $adress->setUser(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setAuthor($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuthor() === $this) {
                $article->setAuthor(null);
            }
        }

        return $this;
    }

    public function getProfile(): ?Profile
    {
        return $this->Profile;
    }

    public function setProfile(?Profile $Profile): self
    {
        $this->Profile = $Profile;

        return $this;
    }

}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use App\Repository\CategoryRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BlogController extends AbstractController
{
    #[Route('/blog', name: 'app_blog')]
    public function index(): Response
    {
        return $this->render('blog/index.html.twig', [
            'controller_name' => 'BlogController',
            'id' => 200,
            'name' => "2cent"
        ]);
    }

    #[Route('/', name:'app_root')]
    public function root(): Response
    {
        return new Response('Hello World');
    }

    #[Route('/blog/{id}/{name}', name: 'app_blog_value', requirements: ["name"=>"[a-zA-Z]{5,50}", "id"=>"[0-9]{2,6}"])]
    public function indexWithValues(int $id, string $name): Response
    {
        return $this->render('blog/index.html.twig',[
            'id' => $id,
            'name' => $name,
            'controller_name' => 'LeRu',
        ]);
    }

    #[Route('/blog/articles', name: 'app_blog_articles')]
    public function showArticles(ArticleRepository $repoArticle, CategoryRepository $repoCategory): Response
    {
        $articles = $repoArticle->findAll();
        $categories = $repoCategory->findAll();
        //dd($articles); //dd siginifie dump and die, donc affichage "brut" et arrêt de l'éxécution
        return $this->render('blog/index.html.twig', [
            'articles' => $articles,
            'categories' => $categories,
        ]);
    }

    // #[Route('/blog/article/{id}', name: 'app_single_article_id')]
    // public function singleId(ArticleRepository $repoArticle, $id): Response
    // {
    //     $article = $repoArticle->findOneById($id); //on peut rechercher n'importe quel attribut de l'entité
    //     return $this->render('blog/single.html.twig', ['article' => $article,]);
    // }

    #[Route('/blog/article/{slug}', name: 'app_single_article')]
    public function single(ArticleRepository $repoArticle, CategoryRepository $repoCategory, string $slug): Response
    {
        $article = $repoArticle->findOneBySlug($slug); //on peut rechercher n'importe quel attribut de l'entité
        $categories = $repoCategory->findAll(); //recherche de toutes les catégories pour les afficher dans le header
        return $this->render('blog/single.html.twig', ['article' => $article,'categories'=>$categories,]);
    }


    #[Route('/blog/category/{slug}', name: 'app_single_category')]
    public function single_category(CategoryRepository $repoCategory,string $slug): Response
    {
        $categories = $repoCategory->findAll(); //recherche de toutes les catégories pour les afficher dans le header
        $category = $repoCategory->findOneBySlug($slug);
        $articles = [];
        $articles = $category->getArticles(); //on peut rechercher n'importe quel attribut de l'entité
        return $this->render('blog/articles_by_category.html.twig', ['articles' => $articles,'categories'=>$categories, 'category'=>$category]);
    }


}

templates/blog/articles_by_category.html.twig
{% extends 'base.html.twig' %}

{% block title %}The Blog{% endblock %}

{% block body %}
    <div class="category-infos"><strong>Articles de la catégorie : </strong>{{category.name}}</div>
    <div class="articles-infos"><strong>{{articles | length}}</strong> article(s) publié(s) </div>
    <div class="articles">
        {% for article in articles %}
            <a href="{{ path('app_single_article', {'slug': article.slug} ) }}" class="article-item">
                <div class="article-item">
                    <div class="article-image">
                        <img src={{article.imageUrl}} alt="Image de l'article : {{article.title}}">
                    </div>
                    <div class="article-details flex">
                        <div class="article-author-details">
                            <div class="article-author-picture">
                                <img src={{article.author.profile.picture}} alt="Image de profile de {{article.author.name}}">
                            </div>
                        </div>
                        <div class="article-content-details">
                            <h2 class="article-title">{{article.title}}</h2>
                            <div class="article-createdAt">{{article.fromNow}}</div>
                        </div>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}The Blog{% endblock %}

{% block body %}
    <div class="articles">
        {% for article in articles %}

            <a href="{{ path('app_single_article', {'slug': article.slug} ) }}" class="article-item">
            <div class="article-item">
                <div class="article-image">
                    <img src={{article.imageUrl}} alt="Image de l'article : {{article.title}}">
                </div>
                <div class="article-details flex">
                    <div class="article-author-details">
                        <div class="article-author-picture">
                            <img src={{article.author.profile.picture}} alt="Image de profile de {{article.author.Tp4bd}}">
                        </div>
                    </div>
                    <div class="article-content-details">
                        <h2 class="article-title">{{article.title}}</h2>
                        <div class="article-createdAt">{{article.fromNow}}</div>
                    </div>
                </div>
            </a>
                        <div class="article-createdAt">{{article.FromNow | date("d/m/Y")}}</div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/single.html.twig
{% extends 'base.html.twig' %}

{% block title %}The Blog{% endblock %}

{% block body %}
    <div class="single-article">
        <div class="article-image">
            <img src={{article.imageUrl}} alt="Image de l'article : {{article.title}}">
        </div>
        <div class="article-details flex">
            <div class="article-author-details">
                <div class="article-author-picture">
                    <img src={{article.author.profile.picture}} alt="Image de profile de {{article.author.name}}">

                </div>
            </div>
            <div class="article-content-details">
                <h2 class="article-title">{{article.title}}</h2>
                <div class="article-createdAt">{{article.fromNow}}</div>
                <div class="article-category flex warp">
                    {% for category in article.categories %}
                        <div class="article-category-item badge">
                            <a href="{{path('app_single_category',{'slug':category.slug})}}">{{category.name}} {{category.articles | length}} article(s) publié(s)</a> 
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}